pipeline{

    agent any

    stages{

       stage('Git Checkout'){

        steps{

           git branch: "main",url: "https://github.com/sumitkbhagat/mrdevops_java_app.git"
        }
        
    }
}